macos_min_version:
  - 10.13  # [osx and x86_64]
  - 11.3  # [osx and arm64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.13  # [osx and x86_64]
  - 11.3  # [osx and arm64]
MACOSX_SDK_VERSION:        # [osx]
  - "10.13"                # [osx and x86_64]
  - "11.3"                 # [osx and arm64]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.13.sdk        # [osx and x86_64]
  - /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk  # [osx and arm64]
