{% set version = "2.6.2" %}

package:
  name: nlopt
  version: {{ version }}

source:
  fn: nlopt-{{ version }}.tar.gz
  url: http://ab-initio.mit.edu/nlopt/nlopt-{{ version }}.tar.gz
  md5: c6986c0d7e35dd8cd3aa6ec6a85806f9

build:
  number: 2
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - cmake         # [win]
    - swig
    - python
    - numpy 1.8.*   # [not (win and (py35 or py36))]
    - numpy 1.9.*   # [win and py35]
    - numpy 1.11.*  # [win and py36]

  run:
    - python
    - numpy >=1.8   # [not (win and (py35 or py36))]
    - numpy >=1.9   # [win and py35]
    - numpy >=1.11  # [win and py36]

test:
  imports:
    - nlopt

about:
  home: http://ab-initio.mit.edu/nlopt
  license: LGPL 2.1
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
