{% set version = "2.7.1" %}

package:
  name: nlopt
  version: {{ version }}

source:
  url: https://github.com/stevengj/nlopt/archive/v{{ version }}.tar.gz
  sha256: db88232fa5cef0ff6e39943fc63ab6074208831dc0031cf1545f6ecd31ae2a1a
  patches:
    - pep3149.patch

build:
  number: 0
  skip: True  # [python_impl == 'pypy']
  run_exports:
    - {{ pin_subpackage('nlopt', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - swig
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nlopt

about:
  home: https://nlopt.readthedocs.io
  doc_url: https://nlopt.readthedocs.io
  dev_url: https://github.com/stevengj/nlopt/
  license: LGPL-2.1-or-later AND MIT
  license_family: Other
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
