travis:
  secure:
    BINSTAR_TOKEN: G32DRZZq+uuknLNi1nxENOH/U4xgplFIkv206sDaoGkSJAsGqfIlERtp8aYlbvi3bzjayr87qiDmMsljqS7RML0yS2Ljus7ksr9fswNxx4ejNhU9DqCUDCnbhzj5TNNnrHyeihqyELkzOKtdOo64Gtslms0LAonJB/Iz4lPeAcF3GvfEhbq/nKq7D28d7ofMnbyDebVwElv3D62wQLRtKgS5TCgNkkvJ0G9vsq81mSrseDHt9HaxHc7FM9/swiBPN3UFtyBerbnXvknaSeHzZVpsKgrqPa7hATVz1tQvBpim+aWjAzz/OA7Rpc6/BTBphgFJeUHXxWHLIj2qBnfaq3m9cku0LGvsIC45fS7/gIH3PRqpAgNhtt/kPjx8IUBKKlofVI3aTWl8wRCBQVTic0Z+fMrzcZC9bpimT+CJosozW3EXSkKttBCS35NlKLk9ukTvVGi5uE0Fe8FVqH+8T8KYE3uvvx88CvNh7f2p09Ua9oYi2EKAJ2e6CTIOEjPbQh/lVASJV1u9ddW0alsy7FK9jL2kPUg11nbZAWLtw++ySszgViT2HHS6aQIvR7MzFssC6mOMYkxzNGLjURyMYm1GB2lZ0qI6M1zsdlYP8NKcTW/sY+Fx4FRmuY/TbVCMHJTJKJValqQdA2KhDtu9V2BWHDrsdYhELzTQFU7FEmA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
