travis:
  secure:
    BINSTAR_TOKEN: NBI0l/CtmF2O3jIXSxYVmhSS/Eg8SfDBRiXQla794VoXGp647maEPIMhorUy9DEV5TJBkWSazevAexnUx/2L/p5AqN9TEU6/ACX/DPqR6NQxp/+HFRrjxG21wwKtACHTuy+YOi/PrBHJMBFYwjdjCsYi6NVqkdg482pJXgKoparkUaDsFcqLvU7mFHRKRPtCoJ+hUiQU/ZGjdflnM28NujIYlFuhd+OVJdMvtewIKq4+i7GUKWH01+luynRwKLKQeDRGiUEyJ8TjY/xzVjh/V56iwwZx714IVhNe5m7rtx1ZG/PfDjajjfJNFtVWsXB0UR7sO1SiFo6g/zWM3LNj0rhVXHPKcTY23LnBHPkgrwVquAnDZUUPozGSUOL3+sLEYdCZFsxeeX4r0yBRLdhDlvXZrRMlrvAjdgFPEqy/HD7VOhZxYsrkTonXXbgroqVbt9m8BBPwC5uWGeZmhGWj+ZuOhhCpZZF7suJh9BMB2kHqYfADZT0baMUp7QoqP6opsHPAKWUPJaw4koLxFi9hOe8RZtutUh+Bt/olVoCd3yFWHqF67iGXClYj3+Zj7ftZOsodp19EkGxnJrdmIJFuw/Jn6H2V+3OY5ONuJt8yDO3DyEMY8Nk94uO5/czyNksCCjHdoRTG+qe2lTsy/OM4Pf2iKu3It0WYgGVMZpbJ3zk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
